activate-negative-cords: true
# Allow negative cords, example:
# -2523 90 -3000
#
# If this option is in false, transform the cords to positive:
# 2523 90 3000

max-radius: 3000

blacklist-worlds:
  - ExampleWorld
  - ExampleWorld2
  enable: false
  message: "&fThe world is blacklist"